dhis2/settings-app

i18n/module/i18n_module_en.properties
src/settingsKeyMapping.js

This is the fix for https://github.com/dhis2/settings-app/issues/43
NOTE: Before merging this branch and testing, Please merge this pull request in D2-UI: https://github.com/dhis2/d2-ui/pull/39 .
After merging the above, and pushing it to production, merge this pull request. It fixes  https://github.com/dhis2/settings-app/issues/43
@nicolayr  and @Markionium  Please let me know if i have missed something.

Only allow positive numbers for factorDeviation

---

src/oauth2-client-editor/OAuth2ClientEditor.component.js

Partial fix for https://github.com/dhis2/settings-app/issues/47

Oauth2Clients Component should use FormBuilder

---

i18n/module/i18n_module_en.properties
src/metadata-settings/metadataSettings.component.js
src/settingsKeyMapping.js

Hi Nicolay,
This PR is backported version of #91 
Thanks

#91 backported to 2.25

---

src/settingsCategories.js
src/settingsKeyMapping.js

I think it was just a matter of deleting the objects below. Please check

Removes monitoring section and key mappings

---

i18n/module/i18n_module_en.properties
src/settingsCategories.js
src/settingsKeyMapping.js

Only had to add some configuration to get this to work

Adds dropdown for keySqlViewMaxLimit

---

src/settingsKeyMapping.js

fix(access): change key input fields to password fields

---

package.json
yarn.lock

It's allright, they've been working on it since apr. 2018: https://github.com/webpack/webpack/issues/7074

fix: set NODE_ENV for webpack prod build

---

i18n/module/i18n_module_en.properties
src/app.component.js
src/form-fields/file-upload.js
src/form-fields/multi-toggle.js
src/localized-text/LocalizedAppearanceEditor.component.js
src/metadata-settings/metadataSettings.component.js
src/oauth2-client-editor/OAuth2ClientEditor.component.js
src/oauth2-client-editor/oauth2Client.actions.js
src/settings-app.js
src/settingsActions.js
src/settingsCategories.js
src/settingsFields.component.js
src/settingsKeyMapping.js
src/theme.js

https://jira.dhis2.org/browse/DHIS2-6161

DHIS2-6161 - add analytics system setting

---

.travis.yml

Fixed the build for #v30 so I can get my other PR based on that branch to pass. Travis issue related to the build failure: https://github.com/travis-ci/travis-ci/issues/10113

chore: remove travis cache

---

src/settingsCategories.js
src/settingsKeyMapping.js

fix: remove keyInstanceBaseUrl field from the server section

---

src/oauth2-client-editor/OAuth2ClientEditor.component.js
webpack.config.js

See https://github.com/dhis2/settings-app/pull/155

fix(oauth-client): backport dhis2-7588 to v32

---

i18n/module/i18n_module_en.properties
package.json
src/settingsCategories.js
src/settingsKeyMapping.js
yarn.lock

I have been unable to completely verify that this fix works, because the dhis2-core version that applies this accepts the new key `keyBingMapsApiKey` was not available yet, at the time of writing. However, this issue was flagged as very urgent and since I'm off tomorrow I created this PR anyway.
So before merging, please verify that updating this field works properly and doesn't produce a 409.

feat: add field for bing maps api key to server section

---

src/settingsCategories.js

fix: move bing and google maps api keys same place

---

src/settingsCategories.js
src/settingsKeyMapping.js

See https://jira.dhis2.org/browse/DHIS2-10075

feat(analytics): remove skip zero values in analytics tables-setting

---

i18n/module/i18n_module_en.properties
i18n/module/i18n_module_nb.properties
src/settingsCategories.js
src/settingsKeyMapping.js

Adds in keyGatherAnalyticalObjectStatisticsInDashboardViews under General.

feat: add support for updating favorite data statistics [DHIS2-9554]

---

i18n/module/i18n_module_en.properties
src/settingsCategories.js
src/settingsKeyMapping.js

This pull request is to add in the settings created by https://jira.dhis2.org/browse/DHIS2-10291.
These settings are to be used for controlling dashboard item view options. Another PR has been submitted for making use of the settings within the dashboards app: https://github.com/dhis2/dashboard-app/pull/1472

feat: Settings to restrict view options of dashboard items (DHIS2-7630)

---

i18n/module/i18n_module_en.properties
src/settingsCategories.js
src/settingsKeyMapping.js

* adds keyCountPassiveDashboardViewsInUsageAnalytics under General

feat: add keyCountPassiveDashboardViewsInUsageAnalytics [DHIS2-7016]

---

i18n/module/i18n_module_en.properties

@scottrusspatrick: this updates the settings names [as you requested in Jira](https://jira.dhis2.org/browse/DHIS2-7630?focusedCommentId=39901&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39901)

fix: update settings names [DHIS2-7630]

---

src/settingsCategories.js

This moves the options shown below from the appearance section to the analytics section.

fix: move dashboard behaviour-related settings (2.36.0)

---

src/settingsKeyMapping.js

This PR updates the settings key names related to dashboard behaviour to match those used in the `v36` branch.

chore: update settings key names for dashboard behaviour

---

i18n/en.pot
src/form-fields/file-upload.js
src/settingsFields.component.js

Closes https://jira.dhis2.org/browse/DHIS2-10783

fix: show alert if custom logo upload succeeds or fails

---

src/App.js
src/settingsCategories.js
src/settingsKeyMapping.js

v37 backport of https://github.com/dhis2/settings-app/pull/887

feat(analytics): add default org unit group set and level for maps (v37)

---

src/App.js
src/settingsCategories.js
src/settingsKeyMapping.js

Closes https://jira.dhis2.org/browse/DHIS2-11704.
Add configuration for new org unit layer in the Maps application.

feat(analytics): add default org unit group set and level for maps

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

v37 backport of https://github.com/dhis2/settings-app/pull/890

feat(analytics): facility map layer settings (v37)

---

src/settingsCategories.js
src/settingsKeyMapping.js

Backport of https://github.com/dhis2/settings-app/pull/900

feat: add setting startModuleEnableLightweight [DHIS2-12060]

---

i18n/en.pot
src/settingsFields.component.js
src/settingsKeyMapping.js

fix: Analytics tab - put the internal maps before the external, and remove Google options

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

v37 backport of https://github.com/dhis2/settings-app/pull/933

feat: zero data values in analytics tables setting (v37)

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Closes https://jira.dhis2.org/browse/DHIS2-12515

feat: zero data values in analytics tables setting

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Closes https://jira.dhis2.org/browse/DHIS2-12099

feat: system update notifications setting

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

v38 backport of https://github.com/dhis2/settings-app/pull/950

feat: system update notifications setting (v38)

---

src/settingsKeyMapping.js

Adds 500k and 1M as analytics and sql view max limit options.

feat: add more analytics/sql view max limit options (DHIS2-12521)

---

src/settingsKeyMapping.js

Backports https://github.com/dhis2/settings-app/pull/965

feat: add more analytics/sql view max limit options

---

src/settingsKeyMapping.js

Backport of https://github.com/dhis2/settings-app/pull/990

fix: add more analytics/sql view max limit options

---

src/settingsCategories.js

Fixes [DHIS2-8860](https://jira.dhis2.org/browse/DHIS2-8860)

fix: remove duplicate entry of keyAnalysisRelativePeriod

---

src/settingsCategories.js

v38 backport for https://github.com/dhis2/settings-app/pull/1053

fix: remove duplicate entry of keyAnalysisRelativePeriod (v38)

---

src/settingsCategories.js

v36 backport for https://github.com/dhis2/settings-app/pull/1053

fix: remove duplicate entry of keyAnalysisRelativePeriod (v36)

---

src/settingsCategories.js

v37 backport for https://github.com/dhis2/settings-app/pull/1053

fix: remove duplicate entry of keyAnalysisRelativePeriod (v37)

---

src/settingsActions.js

[DHIS2-13857](https://dhis2.atlassian.net/browse/DHIS2-13857) backport for v37

fix: assume field is a default field type if no mapping is found (v37)

---

src/settingsActions.js

[DHIS2-13857](https://dhis2.atlassian.net/browse/DHIS2-13857) backport for v38

fix: assume field is a default field type if no mapping is found (v38)

---

src/settingsActions.js

[DHIS2-13857](https://dhis2.atlassian.net/browse/DHIS2-13857) backport for v39

fix: assume field is a default field type if no mapping is found (v39)

---

src/settingsActions.js

[DHIS2-13857](https://dhis2.atlassian.net/browse/DHIS2-13857) backport for patch/2.39.0

fix: assume field is a default field type if no mapping is found (patch-2.39.0)

---

src/App.js

Backport for [DHIS2-13859](https://dhis2.atlassian.net/browse/DHIS2-13859) / [PR-1106](https://github.com/dhis2/settings-app/pull/1106)

fix: update locales import [DHIS2-13859] (v37)

---

src/App.js

Backport for [DHIS2-13859](https://dhis2.atlassian.net/browse/DHIS2-13859) / [PR-1106](https://github.com/dhis2/settings-app/pull/1106)

fix: update locales import [DHIS2-13859] (v38)

---

src/App.js

Backport for [DHIS2-13859](https://dhis2.atlassian.net/browse/DHIS2-13859) / [PR-1106](https://github.com/dhis2/settings-app/pull/1106)

fix: update locales import [DHIS2-13859] (v39)

---

i18n/en.pot
src/form-fields/drop-down.js
src/settingsFields.component.js
src/settingsKeyMapping.js

backport of https://github.com/dhis2/settings-app/pull/1120

fix: add warning for calendar update [DHIS2-7422] (2.39)

---

i18n/en.pot
src/form-fields/drop-down.js
src/settingsFields.component.js
src/settingsKeyMapping.js

backport of https://github.com/dhis2/settings-app/pull/1120

fix: add warning for calendar update [DHIS2-7422] (2.38)

---

i18n/en.pot
src/form-fields/drop-down.js
src/settingsFields.component.js
src/settingsKeyMapping.js

backport of https://github.com/dhis2/settings-app/pull/1120

fix: add warning for calendar update [DHIS2-7422] (2.37)

---

i18n/en.pot
src/localized-text/LocalizedAppearanceEditor.component.js

Backport of https://github.com/dhis2/settings-app/pull/1259

fix: appearance translations [DHIS2-15662] v40

---

i18n/en.pot
src/localized-text/LocalizedAppearanceEditor.component.js

Backport of https://github.com/dhis2/settings-app/pull/1259

fix: appearance translations [DHIS2-15662] v39

---

src/App.module.css

v38 Backport of https://github.com/dhis2/settings-app/pull/1271

fix: extend container height [DHIS2-15875] v38

---

src/App.module.css

v39 Backport of https://github.com/dhis2/settings-app/pull/1271

fix: extend container height [DHIS2-15875] v39

---

src/App.module.css

v40 Backport of https://github.com/dhis2/settings-app/pull/1271

fix: extend container height [DHIS2-15875] v40

---

src/settingsFields.component.js

Backport of https://github.com/dhis2/settings-app/pull/1290

fix: update info icons [DHIS2-10834] (v39)

---

src/settingsFields.component.js

Backport of https://github.com/dhis2/settings-app/pull/1290

fix: update info icons [DHIS2-10834] (v38)

---

src/settingsFields.component.js

Backport of https://github.com/dhis2/settings-app/pull/1290

fix: update info icons [DHIS2-10834] (v40)

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Backport of https://github.com/dhis2/settings-app/pull/1296

fix: remove keyAnalyticsMaintenanceMode [DHIS2-16534]

---

package.json

Updates app version (for continuous release migration)

chore: update app version

---

d2.config.js

update app title to `System Settings`

chore: update app title

---

.github/workflows/dhis2-verify-app.yml

update the github action to allow release to apphub

chore: update verify-app github action

---

d2.config.js

BREAKING CHANGE: adding AppHub ID to enable continuous release

chore: add apphubid

---

i18n/en.pot
src/settingsCategories.js
src/settingsFields.component.js
src/settingsKeyMapping.js

This is a backport (v40) of https://dhis2.atlassian.net/browse/DHIS2-13866

fix: credentialsExpiresReminderInDays [DHIS2-13866] (v40)

---

src/settingsKeyMapping.js

Backport of https://github.com/dhis2/settings-app/pull/1352

fix: pass valid locale for number formatting [DHIS2-17709] (v39)

---

src/settingsKeyMapping.js

Backport of https://github.com/dhis2/settings-app/pull/1352

fix: pass valid locale for number formatting [DHIS2-17709] (v40)

---

i18n/en.pot

PR to trigger release (also updates en.pot file)

fix: update translations, trigger release

---

src/App.jsx

Fixes the prefix logic for https://dhis2.atlassian.net/browse/DHIS2-19308
- v42: ''
- v41 and earlier: app:

fix: update prefix

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Implements [DHIS2-19128](https://dhis2.atlassian.net/browse/DHIS2-19128)
---
This update enhances automatic and manual storage management for the Notifier API (/api/system/tasks and /api/system/taskSummaries) by introducing new system settings to control message limits, data retention, and cleanup behavior.
[DHIS2-19128]: https://dhis2.atlassian.net/browse/DHIS2-19128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add notification settings category and related configurations
