src/form-fields/file-upload.js

Issue 14: https://github.com/dhis2/settings-app/issues/14
I added a simple style object that gets set as the style for the img inside the Dialog component. I was not sure if you guys like to do styles via JavaScript, but it looks like you already did the same for the `bodyStyle`. Also followed the dangling comma convention.
It should at least handle the following two cases:
1. Large overflowing horizontal image:
2. Large overflowing vertical image:

addressing issue 14: https://github.com/dhis2/settings-app/issues/14

---

src/oauth2-client-editor/OAuth2ClientEditor.component.js

Fixes bug that prevented the edit OAuth clients to be edited
- The problem was that when setting `this.clientModel` was created, Object.assign would try to set the `favorite` property on the newly created model instance, but this property is non-writable.
- Instead, the incoming model is used directly by the edit form, which makes more sense conceptually as well.
NB: I didn't request any reviewers on this PR because I already discussed the solution with @varl during a call.

Dhis2 2785/cannot edit oauth2 clients

---

src/settingsKeyMapping.js

setting **includeEmpty: false** will prevent null being set to keyStyle.

set includeEmpty: false

---

src/app.component.js

I think that the inline styles that were there previously used to work with an older version of Material UI. In the current version they don't and I think showing the snackbar in the center is fine, so I just removed these styles.

Show snackbar horizontally centered instead of off-canvas

---

i18n/module/i18n_module_en.properties
src/form-fields/check-box.js
src/settingsCategories.js
src/settingsFields.component.js
src/settingsKeyMapping.js

Adding the new checkboxes was just a matter of adding some config. But then I noticed the CheckBox kept throwing developer warnings about changing from a controlled to an uncontrolled component, so I fixed that too.

DHIS2-2 169 system setting for relative periods in analytics apps

---

src/form-fields/check-box.js

- After refactoring the CheckBox to a stateless function, the messaging section broke
- It all went wrong here, because you can't extend a function https://github.com/dhis2/settings-app/blob/76dbda97e583f18713f4e3f3c5ce936e59103c02/src/settingsFields.component.js#L66
- To fix it, for now, I've just rewrote the CheckBox as a class again.
I don't see this as a proper solution, it's just a quick fix that has very little chance of breaking other stuff.
The proper solution would be to stop using inheritance and refactor `wrapUserSettingsOverride` to a HOC or something. But really, when you look at that whole file `src/settingsFields.component.js`, it's way too big and complex. So instead I have made a new JIRA issue for refactoring the app a bit: https://jira.dhis2.org/browse/DHIS2-6537

fix: messaging-section

---

i18n/module/i18n_module_en.properties
src/form-fields/check-box.js
src/settingsFields.component.js
src/settingsKeyMapping.js

I initially tried adding separate `SectionLabel` component, because that seemed like the most elegant solution. My idea was to then add an arbitrary object to the `src/settingsKeyMapping.js`, just above the first item in that section: `keyHideDailyPeriods `.
But unfortunately that approach wouldn't work for two reasons:
- `src/settingsFields.component.js` loops through the setting-keys returned from the server, not the ones defined in `src/settingsKeyMapping.js`, so it would simply skip it.
- Since `settingsKeyMapping` is an object, not an array, we'd have to give every new `SectionLabel` a unique key, which would make things pretty confusing.
So in the end I went for the easiest solution: just render a section label above the checkbox, if a `sectionLabel` prop has been provided. This was …

feat(checkbox): add sectionLabel prop to checkbox (DHIS2-6842)

---

src/localized-text/LocalizedAppearanceEditor.component.js

Now reading keyUiLocale from settingStore instead of d2.system.settings, because settingsStore is not cleared

fix: appearance-settings

---

src/oauth2-client-editor/OAuth2ClientEditor.component.js
webpack.config.js

The problem here was that the editAction method had not been bound to the component instance and as a result `this.setState` was not available in the function.
I had a problem running this app locally. All proxied requests were trying to set authorisation headers and this was breaking the session. So I removed that part. This will mean that you can only run this app in development mode after you have logged in to your local dhis2-core instance. I don't think this is a problem, because that's what most of our apps do.
I will also have to backport this to v32 and v33.

fix(oauth-client): enable editing (DHIS2-7588)

---

src/app.component.js
src/settingsFields.component.js

The following should be present:
- The `form` element should have `autocomplete="off"`
- In the email section, the input elements for `password` should have `autocomplete="new-password"`

fix(forms): prevent autocomplete on form, username and password fields

---

src/localized-text/LocalizedAppearanceEditor.component.js
src/settings-app.js
src/settingsKeyMapping.js

Prior to this fix, both the DB-locales and the UI-locales dropdown were populated with the same options.

fix(appearance): populate db dropdown with db locales

---

i18n/module/i18n_module_en.properties
package.json
src/localized-text/LocalizedAppearanceEditor.component.js
src/settingsActions.js
webpack.config.js

- The endpoint now accepts JSON payloads so I was able to stop using custom headers for text/plain
- ~For now, we are just editing the localized values here. We have removed support for editing default values, because it is undecided if that is required at all, see this [JIRA issue](https://jira.dhis2.org/browse/DHIS2-8182).~ After discussing with @amcgee it was decided that it'd be better to keep support for editing the default/fallback values should still be supported too. That makes the code quite a bit more complex. Hopefully we can clean it up after 8182 is done.
---
ON HOLD: Currently we are working with an endpoint that only accepts plain text requests. This is going to change, and this will allow me to clean the code up a bit
I think this comment explains it all really 🤕 …

fix: adjust localised appearance settings to new endpoint implementation

---

src/settingsActions.js

There was a problem in https://github.com/dhis2/settings-app/pull/375:
- After updating a localized setting this value would be updated in the database correctly
- But it would also update the `settingStore.state`, which should have only been containing the default values
This fix only updates the settng-store state when a field is not a localized appearance setting. Effectively this covers the default value of an appearance setting, and any other (non-localised) field.

fix: prevent updating setting-store-state from localized-settings

---

i18n/module/i18n_module_en.properties
package.json
src/localized-text/LocalizedAppearanceEditor.component.js
src/settingsActions.js
webpack.config.js

I made sure the api version for this version was set to v32.
NOTE: this also includes the changes from https://github.com/dhis2/settings-app/pull/406
Summary (https://github.com/dhis2/settings-app/pull/375):
* fix: adjust localised appearance settings to new endpoint implementation
* fix(localized-appearances): request as json and stop editing defaults
* chore(localized-appearance): remove comment describing old complexities
* chore: remove redundant i18n string
* Revert "chore: remove redundant i18n string"
- This reverts commit 2c660b85e4d01c5f2f3e129fc0920eca060d55f4.
* Revert "chore(localized-appearance): remove comment describing old complexities"
- This reverts commit a621c002892b9f0377003cc924a9a68bdb775693.
* Revert "fix(localized-appearances): request as json and stop editing …

fix: backport dhis2-6128 to v32

---

i18n/module/i18n_module_en.properties
package.json
src/localized-text/LocalizedAppearanceEditor.component.js
src/settingsActions.js
webpack.config.js

I encountered quite a few merge conflicts, which I had to resolve manually, when trying to backport this baby to v31. I've tested things and it all seems to work, but please take a little extra care when testing this one.
NOTE: this also includes the changes from https://github.com/dhis2/settings-app/pull/406
Summary (https://github.com/dhis2/settings-app/pull/375):
* fix: adjust localised appearance settings to new endpoint implementation
* fix(localized-appearances): request as json and stop editing defaults
* chore(localized-appearance): remove comment describing old complexities
* chore: remove redundant i18n string
* Revert "chore: remove redundant i18n string"
- This reverts commit 2c660b85e4d01c5f2f3e129fc0920eca060d55f4.
* Revert "chore(localized-appearance): remove comment …

fix: backport dhis2-6128 to v31

---

i18n/module/i18n_module_en.properties
package.json
src/localized-text/LocalizedAppearanceEditor.component.js
src/settingsActions.js
webpack.config.js

NOTE: this also includes the changes from https://github.com/dhis2/settings-app/pull/406
Summary (https://github.com/dhis2/settings-app/pull/375):
* fix: adjust localised appearance settings to new endpoint implementation
* fix(localized-appearances): request as json and stop editing defaults
* chore(localized-appearance): remove comment describing old complexities
* chore: remove redundant i18n string
* Revert "chore: remove redundant i18n string"
- This reverts commit 2c660b85e4d01c5f2f3e129fc0920eca060d55f4.
* Revert "chore(localized-appearance): remove comment describing old complexities"
- This reverts commit a621c002892b9f0377003cc924a9a68bdb775693.
* Revert "fix(localized-appearances): request as json and stop editing defaults"
- This reverts commit …

fix: backport dhis2-6128 to v33

---

i18n/module/i18n_module_en.properties
src/form-fields/text-field.js
src/localized-text/LocalizedAppearanceEditor.component.js

This backport required some manual intervention in the `text-field.js` due to merge conflicts. I have tested that it works locally.

fix: disable untranslated localized fields and add help texts (v31)

---

src/settingsCategories.js

fix: return cache strategy field to analytics section

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

**DO NOT MERGE**: Wait for the `keyHideBiWeeklyPeriods` system setting to be implemented in the backend first: https://jira.dhis2.org/browse/DHIS2-11166
Adds a checkbox for hiding biweekly periods.
Before:
After:

feat: hide biweekly periods (DHIS2-11165)

---

src/App.js
src/form-fields/file-upload.js
src/metadata-settings/metadataSettings.component.js
src/settingsFields.component.js

Using `null` as a namespace separator may cause issues if we wish to use namespaces in the future, so this PR replaces it with `'-:-'`.

fix: use '-:-' instead of null as i18n namespace separator

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Closes https://jira.dhis2.org/browse/DHIS2-11704
The default org unit group set and level for maps fields were renamed in https://github.com/dhis2/dhis2-core/pull/8643.

feat(analytics): facility map layer settings

---

i18n/en.pot
src/App.js
src/settingsCategories.js
src/settingsFields.component.js
src/settingsKeyMapping.js

Basemaps are used in the maps-app. This setting allows the admin to select which basemap will be shown as the default. The list of possible basemaps comes from two sources - 1) a hardcoded list that is currently only present in the maps-app repository, and 2) external basemaps added by the admin in the maintenance app.
The solution in this PR was to use both the `source` and the `options` properties to get both of these sources of basemaps, and concatenate. This was the least intrusive way to do the implementation, but it could be argued that it is not the cleanest way.
The changes to the .pot file are due to the change made this year to the string extract script to handle plurals. The result of that change was the .po files would now have all the English translations in it, so that it …

feat: add dropdown for default basemap [DHIS2-12155]

---

src/settingsKeyMapping.js

Backport of 91756e382ffc6e99f24945fe602614ad91610a85

feat: add more analytics/sql view max limit options

---

src/settingsCategories.js

Fixes [DHIS2-13110](https://jira.dhis2.org/browse/DHIS2-13110).
Moved settings for display name property and digit group separator from the Appearance to the Analytics section.
Before:
After:

fix: reorganise some analytics settings DHIS2-13110

---

src/App.js
src/localized-text/LocalizedAppearanceEditor.component.js

See [DHIS2-15292](https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15292)
api/locales/db and api/locales/ui have been updated to include the language name its own language (e.g. français, Deutsch, norsk) (`name`) as well as the translation into the user's selected ui language (e.g. French, German, Norwegian) (`displayName`). This change applies as of v41.
**CURRENTLY (v41)**
Without changes, the language drop down will now display only as a list of languages in the own language (e.g. العربية, বাংলা, Bislama)
**AFTER**
With changes, the language drop down shows in the format `العربية - Arabic`, `বাংলা - Bangla`, `Bislama` (where `name` and `displayName` are the same, only one is shown).
Note: The sorting of languages follows the backend logic of sorting by user's UI …

fix: language display [DHIS2-15292]

---

i18n/en.pot
src/localized-text/LocalizedAppearanceEditor.component.js

See ticket: https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15662
- persists language selection between translations [original bug]
- changes default language for editing appearance settings to the DHIS2 system default language [discussed/approved with Karoline+Joe]
- changes text for default language for appearance settings from `System default (fallback)` to `System default ({{language}}` (e.g. `System default (English)`) [discussed/approved with Karoline+Joe]
**Before**
**After**

fix: appearance translations

---

src/App.module.css

See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-15875
**Before:**
**After:**
_Note:_ I thought that just setting the height to 100% should work here, but that did not. Maybe because of something related to existing material ui theme? Hence, I went with 100vh - header bar height, which did work.

fix: extend container height [DHIS2-15875]

---

i18n/en.pot
src/localized-text/LocalizedAppearanceEditor.component.js

Backport of https://github.com/dhis2/settings-app/pull/1259

fix: appearance translations [DHIS2-15662] v38

---

src/settingsFields.component.js

See https://dhis2.atlassian.net/browse/DHIS2-10834
This updates the information icons so that they are not using a button. I've also updated to use our own Tooltip component and have lightly updated the existing CSS to get them in alignment (I did not want to do more comprehensive CSS updates, so this is a bit eyeballed)
**Before**
**After**

fix: update info icons

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

This PR removes keyAnalyticsMaintenanceMode (under analytics section) as it is no longer supported from v40 onwards.
**Before**
**After**

fix: remove keyAnalyticsMaintenanceMode [DHIS2-16534]

---

d2.config.js

set minDHIS2Version in config. (Required for migration to continuous release)

chore: set minDHIS2Version

---

i18n/en.pot
src/settingsKeyMapping.js

See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-10247
This PR updates the label for the corsAllowlist / corsWhitelist items:
Note that while the corsAllowlist now is available from api/configurations and an alias exists for POST to api/configurations/corsAllowist, I have not changed to use these updated api endpoints because unfortunately, this app uses logic that is in d2 to transform the corsWhitelist field to the appropriate payload (https://github.com/dhis2/d2/blob/master/src/system/SystemConfiguration.js#L78). I don't think it is worth updating the d2 dependency at the moment given that api/configuration/corsWhitelist is still maintained and given that we want to overhaul settings app anyway (at which point I assume we will get rid of the dependency to d2)

chore: update allow list language [DHIS2-10247]

---

src/settingsCategories.js
src/settingsFields.component.js
src/settingsKeyMapping.js

The MMVP for this functionality:
- @cooper-joe are you ok with the second HTML input for the HTML template? We're not uploading a file somewhere, this is just an HTML that's saved in the settings so needs to be in a text box.
- what placeholder text should we have?

feat(DHIS2-16944): add login page settings

---

src/settingsActions.js

Right now, when something goes wrong trying to update a setting (wrong permission, missing key...), the app fails silently. This adds a a generic error message (approved by Joe) until we will revisit this again to improve the design and messaging (to try to display the exact error).

fix: show a generic error when updating setting fails

---

d2.config.js

the app name needs to match [the name maintained](https://github.com/dhis2/dhis2-core/blob/master/dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java#L70) in DHIS2 core for bundled core apps.

fix: update app name to match the bundled apps in core

---

i18n/en.pot
src/App.js
src/app.component.js
src/settingsCategories.js

Implements [DHIS2-17592](https://dhis2.atlassian.net/browse/DHIS2-17592)
---
conditional exclusion of the OAuth2 category in the DHIS2 settings app based on the API version. Specifically, the OAuth2 category is hidden and inaccessible when the API version is greater than 41. This change ensures that users do not see or interact with the OAuth2 settings when using versions over 41 of the DHIS2 API.
---
When API version is 41 or below (OAuth2 category visible)
In this screenshot, the OAuth2 category is visible because the API version is 41 or below.
When API version is above 41 (OAuth2 category hidden)
In this screenshot, the OAuth2 category is hidden because the API version is above 41. Additionally, attempting to manually navigate to the OAuth2 page in the browser will redirect you to the …

feat: remove oauth2 from version 42 and above

---

src/settingsKeyMapping.js

See https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-17709
**Before**
**After**
**Automated**: The app has no automated tests, so I'm not adding any with this PR 🤠
**Manual**: Tested app with various languages. Because of the existing logic of the number formatting, it is only applied on some number and there are some surprising variations:
- variants of Arabic (e.g. `Arabic (Sudan)`) return Arabic formatted numbers (e.g. `٢٠٠٬٠٠٠` instead of `200,000`), but Arabic itself returns `200,000`. I checked with Alaa and she said in Sudan, they're used interchangeably; in Egypt people prefer `٢٠٠٬٠٠٠`)
- Bangla returns with Bengali numerals. (not sure if this is expected or not, and I don't know of Bengali speakers to ask for confirmation.
In both cases, I think it's …

fix: pass valid locale for number formatting [DHIS2-17709]

---

i18n/en.pot
src/app.component.js
src/settingsActions.js
src/settingsCategories.js
src/settingsKeyMapping.js

This PR:
- adds the new setting `keyEmbeddedDashboardsEnabled` under Analytics section (see ticket: https://dhis2.atlassian.net/browse/DHIS2-18472)
- adds version control on the settings definitions (this app became continuous release for v41, so previously we have not had to toggle on/off individual settings by version)
- fixes some filtering logic for the search at the category level. For this, I've moved some of the logic for categories filtering by version. We had added a `maximumApiVersion` on the category level to remove oAuth2 after v41, but I noticed when adding the setting-level versioning that the search functionality was not working properly as we also have to filter categories + settings in the search space
I think the approach here is okay. It would be more efficient to just …

feat: add keyEmbeddedDashboardsEnabled [DHIS2-18472]

---

src/app.component.js
src/settingsActions.js

This fixes a bug with search functionality introduced by https://github.com/dhis2/settings-app/pull/1409 https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-18766.
Because PR #1409 changed the format of the categories/settings information (to allow for feature toggling), the search logic also needs some updates so that the arrays used are in consistent format. Without this change, we were getting an inconsistent format when "search category" was selected.
(This would be good to have a test for, but we have no tests in the app, and I don't want to spend the time right now to figure out how to get tests set up with d2)

fix: search with feature toggling [DHIS2-18766]

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

We might want to remove the select app setting

feat: add global shell settings

---

src/settingsCategories.js
src/settingsKeyMapping.js

fixes issue to make `globalShellEnabled` property appear in v42+. (https://dhis2.atlassian.net/jira/software/c/projects/DHIS2/issues/DHIS2-19290)
I will follow up with separate PRs to add this to documentation.

fix: clean up min version globalShellEnabled

---

src/App.jsx

see https://dhis2.atlassian.net/browse/DHIS2-19308
From @netroms for v42: `just set the value to "dhis-web-dashboard" i.e. drop the app:`

fix: remove v42 app prefix

---

i18n/en.pot
src/settingsCategories.js
src/settingsKeyMapping.js

Makes some updates in the settings app:
- indicates that `multiOrganisationUnitForms` is displayed up through v41 (not used in new aggregate data entry app)
- adds `KeyTrackedEntityMaxLimit` property
- adds note to indicate that Style property applies to Android app.
(These items are noted on https://dhis2.atlassian.net/browse/DHIS2-19366 which primarily addresses updates for the documentation)

fix: settings cleanup [DHIS2-19366]
